baseurl = "https://spaghettidevops.com/"
PygmentsCodeFences = "false"
DefaultContentLanguage = "en"

# Language
languageCode = "en"

# SES friendly url:s
canonifyurls = true

# Frontmatter format
# "yaml", "toml", "json"
metaDataFormat = "toml"

theme = "hugo-bootstrap-premium"

# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "shortname"

# Enable Emoji emoticons support for page content.
# See www.emoji-cheat-sheet.com
enableEmoji = true

[permalinks]
post = "/:year/:month/:day/:slug/"
code = "/:slug/"

[taxonomies]
tag = "tags"
topic = "topics"

[author]
name = "yourname"
email = "yourname@example.com"

[params.theme]
name = "paper"

[params.popover]
enablepopover = false
posturl = "https://zapier.com/hooks/catch/1227563/" # Your zapier post hook.
headerimage = "//placehold.it/1000x600"
expirecookie = 5 #show it again after number of days to visitors that has not subscribed.
cookiename = "mycookie1" #give the cookie a unique name variable (avoid spaces and strange characters).
signupheader = "Join Our Newsletter"
showmodaltimeout = 10000 #show popover modal after time interval in milliseconds.
mouseleave = true #show popover when mouse leaves window: true/false.
modalsize = "" #lg or sm. Empty is md. If phone is detected lg is used.
imagedescription = "Placeholder image for this popover modal optin form"
signuptext = "Signup today for free and be the first to get notified on new updates."
inputplaceholder = "Enter your email"
submitbutton = "Subscribe"
successmessage = "Thanks for your subscription!"
errormessage = "Submitting form failed!"
optin = true #opt-in: true/false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
# You can use markdown here.
BrandImage = "/icon/touch-icon-144-precomposed.png" #top header brand image.
headline = "random"
footline = "random"
description = "A blog without a good description"

# Text for the top menu link, which goes to the root URL for the site.
# Default (if omitted) is "Home".
home = "home"

mailmunchid = "" # Mailmunch site id
#sumomeid = "" # Sumome id

# Show a sidebar menu
showRightSidebar = false
# Select a syntax highlight.
# Check the static/css/highlight directory for options.
highlight = "default"

# Google Analytics.
googleAnalytics = "UA-93718530-1"

# Sidebar social links.
github = "Myprofile" # Your Github profile ID
bitbucket = "" # Your Bitbucket profile ID
linkedin = "" # Your LinkedIn profile ID (from public URL)
googleplus = "Myprofile" # Your Google+ profile ID
facebook = "Myprofile" # Your Facebook profile ID
twitter = "Myprofile" # Your Twitter profile ID
youtube = ""  # Your Youtube channel ID
flattr = ""  # populate with your flattr uid

[blackfriday]
angledQuotes = true
fractions = false
hrefTargetBlank = false
latexDashes = true
plainIdAnchors = true
extensions = []
extensionmask = []

[Languages]
[Languages.en]
weight = 1
copyright = "(c) 2017. All rights reserved." # TODO: dynamic year evaluation
title = "SpaghettiDevops" # Site title

[[Languages.en.menu.main]]
name = "Home"
weight = 1
identifier = "home"
url = "/"
pre = "<i class='fa fa-home' aria-hidden='true'></i>"

[[Languages.en.menu.main]]
name = "Articles"
weight = 2
identifier = "post"
url = "/post/"
pre = "<i class='fa fa-book' aria-hidden='true'></i>"

[[Languages.en.menu.main]]
name = "About"
weight = 3
identifier = ""
url = "/about"
pre = "<i class='fa fa-user'aria-hidden='true'></i>"
